name: skynet-webportal CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]
    
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn
    - name: Build production bundle
      run: yarn build
      env:
        GATSBY_API_URL: "https://siasky.net"
    - name: Cypress run
      uses: cypress-io/github-action@v1
      with:
        start: npx http-server public --port 8000
        wait-on: "http://localhost:8000"
